<script>
 import {tick,createEventDispatcher} from 'svelte';
 export let open=false;
 const dispatch=createEventDispatcher();let dialog,priorFocus;
 $:if(dialog&&open&&!dialog.open){priorFocus=document.activeElement;dialog.showModal();tick().then(()=>dialog.querySelector('button')?.focus());}
 $:if(dialog&&!open&&dialog.open){dialog.close();(priorFocus?.isConnected && priorFocus.getClientRects().length ? priorFocus : document.querySelector('[data-help-trigger]')?.getClientRects().length ? document.querySelector('[data-help-trigger]') : document.querySelector('[data-settings-trigger]'))?.focus({preventScroll:true});}
</script>
<dialog bind:this={dialog} aria-label="Help and keyboard shortcuts" on:cancel|preventDefault={()=>open=false}>
 <header><h2>Help</h2><button class="dw-btn-secondary" on:click={()=>open=false}>Close Help</button></header>
 <h3>Find something you said</h3><p>Search entries by words, tags, title, or filename. Search spans the library. Narrow it with the date rail, Starred, MayDos, or Filters. The result summary names the scope; Clear filters restores it. Words search works without a model connection.</p>
 <h3>Read and listen without losing your place</h3><p>Select an entry to open the reader beside the list. Previous and Next follow your current results. On a small screen, Back to entries returns to your list position. Transcript shows cleaned speech when available; Original keeps the raw transcription.</p><p>Select passage text to copy it. The time button starts audio at that passage. Copy appears when a passage is focused or hovered; Copy all is in the reader. Playback speed, Follow and Find are reader controls. Audio unavailable does not prevent reading.</p>
 <h3>Capture a recording</h3><p>Record asks for microphone access only when you start. Stop retains a draft; Save acknowledges the saved audio before processing. Retry keeps the same draft after an upload failure. Import accepts audio files without microphone access. Activity shows saved work, waiting for sync writes, progress, and retryable failures.</p><p>A blocked browser microphone needs a secure browser context and permission. Import remains available. Do not change network exposure just to enable recording.</p>
 <h3>Decide whether an action is worth doing</h3><p>MayDos are possible actions, not commitments. New suggestions start as Suggested. Mark one Selected when you choose it, Done after completion, or Dismissed when it does not fit. Changes offer a short Undo. Source reveals the supporting transcript; a timestamp plays it when available.</p><p>Use MayDos and status filters to find entries with actions. Older entries can be extracted in a scoped batch, stopped after the current entry, resumed, or retried only for failures.</p>
 <h3>Organize or recover an entry</h3><p>Reader More contains Assign recording date and Move to Trash. Organization previews both entries on conflict. Keep both is the default; replacement preserves the existing entry in Trash. Unfiled and Holding entries remain readable.</p><p>Move to Trash waits for the server acknowledgment, then offers eight-second Undo. Afterward, Settings → Data and maintenance → Trash can restore it. Restore keeps both when a destination exists. Permanent deletion requires naming and confirming the saved audio and transcript.</p>
 <h3>Fix processing or search</h3><p>Activity shows the failed stage. Cleanup problems leave Original available; configure the host/model in the loaded configuration file, restart, then retry cleanup. Settings shows effective folders, runtimes, destinations, and diagnostics. A words-index rebuild changes only the derived cache.</p><button class="dw-btn-secondary" on:click={()=>{open=false;dispatch('settings');}}>Open Settings and recovery</button>
 <h3>Keyboard shortcuts</h3><dl><dt>/</dt><dd>Focus library search outside text fields</dd><dt>?</dt><dd>Open this Help outside text fields</dd><dt>Enter</dt><dd>Open a focused entry</dd><dt>Escape</dt><dd>Close the current dialog or the reader's open More / Find control</dd><dt>Tab / Shift+Tab</dt><dd>Move between controls; dialogs keep focus inside</dd><dt>Space</dt><dd>Activate focused playback control</dd></dl>
</dialog>
<style>dialog{position:fixed;inset:0 0 0 auto;margin:0;width:min(560px,100vw);max-width:100vw;height:100dvh;max-height:100dvh;padding:20px;box-sizing:border-box;background:#18181b;color:var(--dw-text);border:0;border-left:1px solid var(--dw-border);overflow:auto;}dialog::backdrop{background:#0009;}header{position:sticky;top:-20px;background:#18181b;padding:8px 0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:12px;}h2{font-size:20px;}h3{font-size:17px;margin-top:24px;}p{overflow-wrap:anywhere;line-height:1.6;}button{min-height:44px;}dt{font-weight:600;margin-top:12px;}dd{margin:6px 0;line-height:1.5;}</style>
