<script>
  import {tick,onDestroy,createEventDispatcher} from 'svelte';
  import CleanupRetries from './CleanupRetries.svelte';
  import {copyTranscriptText} from '../entryPresentation.js';
  let copyFeedback='';
  async function copyReport(){const result=await copyTranscriptText(JSON.stringify(health,null,2),navigator.clipboard);copyFeedback=result.error||'Diagnostic report copied.';}
  import TrashPanel from './TrashPanel.svelte';
  import MayDoBackfill from './MayDoBackfill.svelte';
  import TagMaintenance from './TagMaintenance.svelte';
  export let open=false, connected=false, noteFilter='all', section='General';
  const dispatch=createEventDispatcher();
  const sections=['General','Folders','Transcription','Cleanup and MayDos','Search','Data and maintenance','Integrations','About'];
  let dialog,priorFocus,settings=null,health=null,stats=null,probe=null,error='',message='',busy=false,timer,markSelected={},markConfirm=false;
  async function fetchJson(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
  async function refresh(){error='';try{[settings,stats,probe]=await Promise.all([fetchJson('/settings'),fetchJson('/notes/stats'),fetchJson('/tools/probe')]);}catch(e){error=e.message;}}
  async function action(url,body){busy=true;error='';message='';try{const data=await fetchJson(url,body);message=JSON.stringify(data);await refresh();}catch(e){error=e.message;}finally{busy=false;}}
  async function checks(){busy=true;error='';try{health=await fetchJson('/health?fresh=1');}catch(e){error=e.message;}finally{busy=false;}}
  async function scan(){markConfirm=false;markSelected={};await action('/tools/probe',{apply:false});timer=setInterval(async()=>{if(!open){clearInterval(timer);return;}try{probe=await fetchJson('/tools/probe');if(!probe.running)clearInterval(timer);}catch(e){error=e.message;clearInterval(timer);}},1500);}
  $: if(dialog&&open&&!dialog.open){priorFocus=document.activeElement;dialog.showModal();void refresh();tick().then(()=>dialog.querySelector('button')?.focus());}
  $: if(dialog&&!open&&dialog.open){dialog.close();clearInterval(timer);(priorFocus?.isConnected && priorFocus.getClientRects().length ? priorFocus : document.querySelector('[data-settings-trigger]')?.getClientRects().length ? document.querySelector('[data-settings-trigger]') : document.querySelector('[data-settings-trigger]'))?.focus({preventScroll:true});}
  onDestroy(()=>clearInterval(timer));
</script>
<dialog bind:this={dialog} aria-label="Settings" on:cancel|preventDefault={()=>open=false}>
  <header><h2>Settings</h2><button class="dw-btn-secondary" on:click={()=>open=false}>Close Settings</button></header>
  {#if open}
  <nav aria-label="Settings sections">{#each sections as name}<button class="dw-btn-secondary" aria-current={section===name?'page':undefined} on:click={()=>{section=name;error='';message='';}}>{name}</button>{/each}</nav>
  {#if error}<p class="dw-error" role="alert">{error}</p><button class="dw-btn-secondary" on:click={refresh}>Retry loading Settings</button>{/if}
  {#if !settings}<p>Loading effective settings…</p>{:else}
    <h3>{section}</h3>
    {#if section==='General'}<p>The library adapts to the window. Opening an entry keeps a compact list beside its reader. On a small screen, Back to entries returns to your list position.</p><p>Playback speed and Follow are reader controls. Filters and reader position are retained for this browser session. Reduced motion follows your system setting.</p><button class="dw-btn-secondary" on:click={()=>{open=false;dispatch('help');}}>Keyboard shortcuts and reading help</button>
    {:else if section==='Folders'}<p>Audio remains in your configured folders. Watch imports wait for writes to settle.</p>{#each settings.folders.roots as root}<p><code>{root.file}</code> {root.exists?'Available':'Missing · create the folder or correct watch.roots in config'}</p>{/each}<dl><dt>Browser import destination</dt><dd>{settings.folders.browserDropFolder}</dd><dt>Watch settle time</dt><dd>{settings.folders.settleMinutes} minutes</dd><dt>Browser settle time</dt><dd>{settings.folders.browserSettleMs} ms</dd><dt>Watch year folders</dt><dd>{settings.folders.recursiveYears?'Yes':'No'}</dd></dl>
    {:else if section==='Transcription'}<p>Whisper transcribes locally. Saved audio can wait in Activity if processing is unavailable.</p><dl><dt>Python interpreter</dt><dd>{settings.transcription.python}</dd><dt>Model</dt><dd>{settings.transcription.model}</dd><dt>Device / compute type</dt><dd>{settings.transcription.device} / {settings.transcription.computeType}</dd><dt>Worker</dt><dd>{settings.transcription.worker}</dd><dt>Queue</dt><dd>{settings.transcription.queue.active?'Enabled':'Disabled'} · concurrency {settings.transcription.queue.concurrency}</dd><dt>Preprocessing</dt><dd>{settings.transcription.preprocess?'Enabled · requires ffmpeg':'Disabled'}</dd><dt>Vocabulary hints</dt><dd>{settings.transcription.promptTerms.join(', ')||'None'}</dd></dl><p>Worker blocked? Run diagnostics below. Missing Python or faster-whisper requires local runtime setup; you can still read existing transcripts.</p><button class="dw-btn-secondary" disabled={busy||!connected} on:click={checks}>Check transcription setup</button>
    {:else if section==='Cleanup and MayDos'}<p>Cleanup and action extraction send transcript text and tags to the configured model host. Saved transcripts and MayDos remain usable when this optional service is unavailable.</p><dl><dt>Configured host</dt><dd>{settings.cleanup.machine||'Not configured'}</dd><dt>Model</dt><dd>{settings.cleanup.cleanModel||'Not configured'}</dd><dt>MayDo extraction</dt><dd>{settings.cleanup.available?'Available':settings.cleanup.disabledReason}</dd><dt>Cleanup queue</dt><dd>{settings.cleanup.queue.active?'Enabled':'Disabled'}</dd><dt>Required for startup checks</dt><dd>{settings.cleanup.required?'Yes':'No · optional'}</dd><dt>Save model chats</dt><dd>{settings.cleanup.saveChats?'Enabled':'Disabled'}</dd></dl><p>New cleanup extracts possible actions as Suggested. Existing selections and statuses are preserved. Bulk extraction is under Data and maintenance.</p><button class="dw-btn-secondary" disabled={busy||!connected} on:click={checks}>Test configured services</button>
    {:else if section==='Search'}<dl><dt>Configured mode</dt><dd>{settings.search.search}</dd><dt>Embedding host selection</dt><dd>{settings.search.embedHost}</dd><dt>Embedding model preference</dt><dd>{settings.search.embedModel||'Automatic selection'}</dd><dt>Index</dt><dd>{settings.search.index}</dd><dt>Coverage</dt><dd>{stats?.notes||0} entries · {stats?.embedded||0} embedded</dd></dl><p>Words search works without embeddings. Meaning search sends transcript text and query text to the selected embedding host when enabled. The index is a derived cache; rebuilding never retranscribes audio.</p><button class="dw-btn-secondary" disabled={busy||!connected||stats?.indexing} on:click={()=>action('/tools/index/rebuild',{})}>{stats?.indexing?'Rebuilding…':'Rebuild words index'}</button>
    {:else if section==='Data and maintenance'}
      <button class="dw-btn-secondary" on:click={()=>{open=false;dispatch('activity');}}>Open Activity · processing and retries</button>
      <details open><summary>Trash and recovery</summary><TrashPanel {connected}/></details>
      <details><summary>Extract MayDos from older entries</summary><MayDoBackfill {connected} on:change={event=>dispatch('job',event.detail)}/></details>
      <details><summary>Retry failed cleanup</summary><CleanupRetries {connected} on:activity={()=>{open=false;dispatch('activity');}}/></details>
      <details><summary>Consolidate tags</summary><TagMaintenance {connected}/></details>
      <details><summary>Check pending audio</summary><p>Checks pending files in watched folders. Marking reviewed failures adds unreadable metadata; audio is retained.</p><button class="dw-btn-secondary" disabled={busy||!connected||probe?.running} on:click={scan}>{probe?.running?'Scanning…':'Scan pending audio'}</button>{#if probe?.finishedAt}<p>{probe.bad} failures in {probe.pending} pending files</p>{#each probe.files||[] as hit}<label><input type="checkbox" bind:checked={markSelected[hit.file]} disabled={busy}/><span>{hit.reason}<code>{hit.file}</code></span></label>{/each}{#if probe.files?.length}<label><input type="checkbox" bind:checked={markConfirm}/> Mark selected files unreadable; retain audio</label><button class="dw-btn-secondary" disabled={busy||!connected||!markConfirm||!Object.values(markSelected).some(Boolean)} on:click={()=>action('/tools/probe/mark',{files:Object.keys(markSelected).filter(file=>markSelected[file])})}>Mark reviewed failures</button>{/if}{/if}<button class="dw-text-btn" on:click={()=>{noteFilter='unreadable';open=false;}}>Show unreadable entries</button></details>
      <details><summary>Stable entry identities</summary><p>Add IDs to legacy sidecars in the index, including Holding and Unfiled. IDs survive moves and restores. This updates sidecars; active processing is skipped with a retryable report.</p><button class="dw-btn-secondary" disabled={busy||!connected} on:click={()=>action('/tools/entries/identity',{})}>Backfill entry IDs</button></details>
    {:else if section==='Integrations'}<p>MCP runs locally over stdio. Clients share these configured roots and derived index.</p><pre>{JSON.stringify(settings.integrations.mcp,null,2)}</pre><p>ExoMetaCortex: {settings.integrations.exoMetaCortex}</p>
    {:else}<p>DictaWhisper {settings.version}</p><dl><dt>API endpoint</dt><dd>{settings.network.apiUrl}</dd><dt>Browser origin</dt><dd>{typeof location!=='undefined'?location.origin:''}</dd><dt>Configured exposure</dt><dd>{settings.network.listenHost} · Tailscale {settings.network.tailscale?'enabled':'disabled'}</dd><dt>Allowed browser origins</dt><dd>{settings.network.corsOrigins.join(', ')}</dd></dl><button class="dw-btn-secondary" disabled={busy||!connected} on:click={checks}>{busy?'Checking…':'Run diagnostics'}</button><button class="dw-btn-secondary" on:click={()=>{open=false;dispatch('help');}}>Open task help</button><a href="https://dictawhisper.com" target="_blank" rel="noreferrer">Product documentation</a>{/if}
    {#if health}<details open><summary>Diagnostic results · {health.ok?(health.degraded?'Ready with warnings':'Ready'):'Needs attention'}</summary>{#each ['transcription','cleanup','search','runtime'] as group}<h4>{group==='cleanup'?'Optional cleanup':group==='search'?'Search readiness':group==='transcription'?'Required for transcription':'Runtime and folders'}</h4>{#each health.checks?.filter(check=>(check.group||'runtime')===group)||[] as check}<p>{check.level}: {check.message}</p>{/each}{/each}<button class="dw-btn-secondary" on:click={copyReport}>Copy diagnostic report</button><p role="status">{copyFeedback}</p><details><summary>Plain diagnostic report</summary><pre>{JSON.stringify(health,null,2)}</pre></details></details>{/if}
    <details><summary>Advanced · loaded configuration</summary><p>Effective settings are read-only. Edit this configuration file, then restart DictaWhisper. There is no pending Save in this view.</p><code>{settings.configPath}</code><p>Set the DICTA_CONFIG environment variable to this file to select it explicitly.</p><p>Checkout: <code>pnpm doctor</code></p><p>Installed CLI: <code>dictawhisper doctor</code></p><p>These commands can test runtimes and model connections. Keep paths and journal details private when sharing diagnostics.</p></details>
  {/if}
  {#if message}<pre role="status">{message}</pre>{/if}
  {/if}
</dialog>
<style>dialog{position:fixed;inset:0 0 0 auto;margin:0;width:min(620px,100vw);max-width:100vw;height:100dvh;max-height:100dvh;padding:20px;box-sizing:border-box;background:#18181b;color:var(--dw-text);border:0;border-left:1px solid var(--dw-border);overflow:auto;}dialog::backdrop{background:#0009;}header{position:sticky;top:-20px;background:#18181b;padding:8px 0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:12px;}nav{display:flex;flex-wrap:wrap;gap:6px;margin:16px 0;}h2{font-size:20px;}h3{font-size:18px;}button,summary,input{min-height:44px;}button[aria-current]{border-color:#e8b44b;color:#f2c665;}details{border-top:1px solid var(--dw-border);margin-top:16px;padding:12px 0;}summary{display:flex;align-items:center;cursor:pointer;font-weight:600;}p,label{line-height:1.5;}label{display:flex;gap:10px;align-items:flex-start;margin:12px 0;}dt{font-size:12px;color:#a1a1aa;margin-top:12px;}dd{margin:4px 0;overflow-wrap:anywhere;}code,pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;}button{margin:4px 6px 4px 0;}input{flex-shrink:0;}</style>
